package com.myspace.loan_approval_workshop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Amount")
	private java.lang.Double amount;
	@org.kie.api.definition.type.Label("Approved")
	private java.lang.Boolean approved;
	@org.kie.api.definition.type.Label("Comment")
	private java.lang.String comment;
	@org.kie.api.definition.type.Label("Duration")
	private java.lang.Integer duration;
	@org.kie.api.definition.type.Label("Interest Rate")
	private java.lang.Double interestRate;
	@org.kie.api.definition.type.Label("Monthly Repayment")
	private java.lang.Double monthlyRepayment;

	@org.kie.api.definition.type.Label("Age Pre Qualification")
	private boolean agePreQual;

	@org.kie.api.definition.type.Label("Loan Pre Qualification")
	private boolean loanPreQualification;

	public Loan() {
	}

	public java.lang.Double getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Double amount) {
		this.amount = amount;
	}

	public java.lang.Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(java.lang.Boolean approved) {
		this.approved = approved;
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public java.lang.Integer getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.Integer duration) {
		this.duration = duration;
	}

	public java.lang.Double getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(java.lang.Double interestRate) {
		this.interestRate = interestRate;
	}

	public java.lang.Double getMonthlyRepayment() {
		return this.monthlyRepayment;
	}

	public void setMonthlyRepayment(java.lang.Double monthlyRepayment) {
		this.monthlyRepayment = monthlyRepayment;
	}

	public boolean isAgePreQual() {
		return this.agePreQual;
	}

	public void setAgePreQual(boolean agePreQual) {
		this.agePreQual = agePreQual;
	}

	public boolean isLoanPreQualification() {
		return this.loanPreQualification;
	}

	public void setLoanPreQualification(boolean loanPreQualification) {
		this.loanPreQualification = loanPreQualification;
	}

	public Loan(java.lang.Double amount, java.lang.Boolean approved,
			java.lang.String comment, java.lang.Integer duration,
			java.lang.Double interestRate, java.lang.Double monthlyRepayment,
			boolean agePreQual, boolean loanPreQualification) {
		this.amount = amount;
		this.approved = approved;
		this.comment = comment;
		this.duration = duration;
		this.interestRate = interestRate;
		this.monthlyRepayment = monthlyRepayment;
		this.agePreQual = agePreQual;
		this.loanPreQualification = loanPreQualification;
	}

}